#!/usr/bin/env python3
# uses environment variable

import os
import sys

from twython import Twython, TwythonError
from analyzer import Analyzer
from termcolor import colored

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @user")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    # get user tweets
    # ensure environment variables are set
    if not os.environ.get("API_KEY"):
        raise RuntimeError("API_KEY not set")
    if not os.environ.get("API_SECRET"):
        raise RuntimeError("API_SECRET not set")
    # print(os.environ.get("API_KEY"), os.environ.get("API_SECRET"))
    twitter = Twython(os.environ.get("API_KEY"), os.environ.get("API_SECRET"))

    try:
        tweets = twitter.get_user_timeline(screen_name=sys.argv[1], count=51)
        # print(tweets)
    except TwythonError as e:
        print(e)

    # analyze tweets
    green, red, yellow = 0, 0, 0
    for i in range(len(tweets)):
        # print(i)
        score = analyzer.analyze(tweets[i]['text'].encode('utf-8').lower())
        if score > 0.0:
            # print(colored(":)", "green"))
            green = green + 1
        elif score < 0.0:
            # print(colored(":(", "red"))
            red = red + 1
        else:
            # print(colored(":|", "yellow"))
            yellow = yellow + 1
    print(green, red, yellow)
    # positive, negative, neutral = 0.0, 0.0, 100.0 # initialize as float
    # positive, negative, neutral = float(green/len(tweets))*100, float(red/len(tweets))*100, float(yellow/len(tweets))*100 
    # print(positive, negative, neutral)

if __name__ == "__main__":
    main()